FROM ubuntu:22.04

WORKDIR /opt/worldclimateapi/

RUN apt update && apt install python3 python3-pip -y
RUN apt-get install python3-venv -y
RUN python3 -m venv antenv
RUN /bin/bash -c " source antenv/bin/activate && pip install requests && pip install flask==3.0.*  python-dotenv"

COPY . .

CMD [ "/opt/worldclimateapi/antenv/bin/python3","app.py" ]