trigger:
- ARMvishnu

pool:
  name: 'vishnupool'
  demands:
  - agent.name -equals vishnuagent

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'New Free Trial (kollivenkata07)'
    subscriptionId: 'e3892e0d-01ed-466e-979b-ce235caaf7aa'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG-VA'
    location: 'centralus'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/Pipelines/Infra/ARMTemplates/vm/vm.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)//Pipelines/Infra/ARMTemplates/vm/parameters.json'
    deploymentMode: 'Incremental'
    deploymentOutputs: 'ARMOutputs'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $outputs = ConvertFrom-Json -InputObject '$(ARMOutputs)'
      $vmPublicIP = $outputs.properties.outputs.vmPublicIP.value
      Write-Output "VM Public IP Address: $vmPublicIP"
      # Set the IP address as a pipeline variable if needed
      Write-Host "##vso[task.setvariable variable=vmPublicIP]$vmPublicIP"
