trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'  # Specify the Python version you need


- script: |
    # Add commands to create a ZIP archive of your Python application
    cd Source/WeatherApp
    zip -r $(Build.ArtifactStagingDirectory)/weatherapp.zip .
  displayName: 'Build'

#- script: |
#    apt-get update -y
#    apt-get install python3.11 -y
#    python -m pip install --upgrade pip
#    pip install -r requirements.txt
#    apt-get install zip -y
#    apt-get install python3-venv -y
#    apt-get install pkg-config -y
#    apt-get install libmysqlclient-dev -y
#  displayName: 'Install dependencies'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AppServiceConnection-va'
    appName: 'webappservicepython.azurewebsites.net'
#   package: '$(Build.ArtifactStagingDirectory)/weatherapp.zip'
#   startUpCommand: 'python run.py'  # Specify the startup command for your Python application
  displayName: 'Deploy to Azure Web App'