# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: vishnupool
  vmImage: vishnuagent

stages:
  - stage: "Build"
    displayName: "Build WeatherApp"
    jobs:
      - job: "BuildWeatherapp"
        displayName: 'Build Weatherapp'
        pool: Satyam
        steps: 
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: 'source/weatherapp'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/Apps/weatherapp.zip'
              replaceExistingArchive: true
          
          - task: CopyFiles@2
            displayName: "Copy Infra files"
            inputs:
              SourceFolder: 'Pipelines/Infra/ARMTemplates'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/InfraArm'
          
          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifacts"
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  
  - stage: "DEV"
    displayName: "DEV Deploy"
    dependsOn: Build
    jobs:
      - job: "BuildWeatherapp"
        displayName: 'Build Weatherapp'
        pool: Satyam
        steps: 
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)/downloads'
            
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                # Write your PowerShell commands here.
                
                Get-ChildItem $(System.ArtifactsDirectory)/downloads
    
  - stage: "QA"
    displayName: "QA Deploy"
    dependsOn: DEV
    jobs:
      - job: "BuildWeatherapp"
        displayName: 'Build Weatherapp'
        pool: Satyam
        steps: 
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)/downloads'
            
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                # Write your PowerShell commands here.
                
                Get-ChildItem $(System.ArtifactsDirectory)/downloads