# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: Satyam
  vmImage: LAPTOP-RS36BMKA

parameters:
  - name: env
    displayName: Environment to Deploy
    type: string
    default: Dev
    values:
      - Dev
      - Qa
      - Uat
      - Prod

variables:
  - group: 'Infra-${{ parameters.env }}'
  - name: appserviceNameWeb
    value: dk-weatherapp-web
  - name: appserviceNameApi
    value: dk-weatherapp-api
  - name: PAT
    value: default

stages:
  - stage: "Build"
    displayName: "Build WeatherApp"
    jobs:
      - job: "BuildWeatherapp"
        displayName: 'Build Weatherapp'
        steps: 
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: 'source/weatherapp'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/Apps/weatherapp.zip'
              replaceExistingArchive: true
          
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: 'source/WorldClimateApi'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/Apps/worldclimateapi.zip'
              replaceExistingArchive: true
          
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                # Write your PowerShell commands here.
                echo $(serviceConnection)
                echo ${env:APIVERSION}
                echo $(Build.BuildNumber)
                echo $(Build.BuildId)
                echo $(Build.DefinitionName)_$(Build.DefinitionVersion)_$(Build.RequestedFor)_$(Build.BuildId)
                echo $(System.DefinitionId)
                echo $(Build.BuildUri)
                Write-Host "Hello World"
          
          # - task: AzureCLI@2
          #   inputs:
          #     azureSubscription: 'ADO-WeatherApp-SC-NonProd'
          #     scriptType: 'ps'
          #     scriptLocation: 'scriptPath'
          #     scriptPath: 'Pipelines/Scripts/Azcli/updatepipelinevars.ps1'
          #     arguments: '-organizationName "venkatachaitanya095" -projectName "PythonProjects" -pipelineId $(System.DefinitionId) -variableName "apiversion" -variableValue "1.0.4"'
          #     addSpnToEnvironment: true
          - task: CopyFiles@2
            displayName: "Copy Infra files"
            inputs:
              SourceFolder: 'Pipelines/Infra/ARMTemplates'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/InfraArm'
          
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                # Write your PowerShell commands here.
                
                echo ${env:APIVERSION}

          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifacts"
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
          
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: 'source/WorldClimateApi'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: 'Pipelines/artifacts/(Get-Date).ToString("yyyy-MM-dd-mm")/worldclimateapi.zip'
              replaceExistingArchive: true
          
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                echo "commit all changes "
                git config user.name "Satyam"
                git config user.email "satyam.dasari51@gmail.com"
                git fetch
                git checkout -b "Satyam/$(Build.SourceBranchName)"
                git add --all
                git commit -m "Solution Backup"
                echo "push code to new repo "
                git push https://$(PAT)@dev.azure.com/venkatachaitanya095/PythonProjects/_git/PythonFlaskMarketWeatherApp Satyam/$(Build.SourceBranchName)

  - stage: "DevInfra"
    displayName: "DEV Deploy: Infra"
    dependsOn: Build
    jobs:
      - deployment: "DeployInfra"
        displayName: 'Deploy Infra'
        pool: Satyam
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps: 
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    downloadPath: '$(System.ArtifactsDirectory)/downloads'
                
                - task: PowerShell@2
                  inputs:
                    targetType: 'inline'
                    script: |
                      # Write your PowerShell commands here.
                      
                      echo ${env:APIVERSION}
                    
                - task: AzureResourceManagerTemplateDeployment@3
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: $(serviceConnection)
                    subscriptionId: $(subscriptionId)
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: $(resourceGroup)
                    location: 'North Central US'
                    templateLocation: 'Linked artifact'
                    csmFile: '$(System.ArtifactsDirectory)/downloads/drop/InfraArm/appserviceSatyam/appservice.json'
                    csmParametersFile: '$(System.ArtifactsDirectory)/downloads/drop/InfraArm/appserviceSatyam/parameters-dev.json'
                    deploymentMode: 'Incremental'
  

  - stage: "DevWebApp"
    displayName: "DEV Deploy: Weather App"
    dependsOn: DevInfra
    jobs:
      - deployment: "DeployApp"
        displayName: 'Deploy App'
        pool: Satyam
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps: 
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    downloadPath: '$(System.ArtifactsDirectory)/downloads'
                
                - task: AzureRmWebAppDeployment@4
                  displayName: "Deploy WeatherApp Web"
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'ADO-WeatherApp-SC-NonProd'
                    appType: 'webAppLinux'
                    WebAppName: '${{ variables.appserviceNameWeb }}-${{ parameters.env }}'
                    packageForLinux: '$(System.ArtifactsDirectory)/**/weatherapp.zip'
                    StartupCommand: 'apt-get install python3-pip -y;apt-get install zip -y;apt-get install python3-venv -y;python3 -m venv antenv;source antenv/bin/activate;apt-get install pkg-config -y --ignore-missing;apt-get install dos2unix;apt-get install default-libmysqlclient-dev -y --ignore-missing;FILEPATH=$(find . -type f -name odbc17.sh);dos2unix "$FILEPATH";bash $FILEPATH;python3 app.py'
                  
  - stage: "DevWebAPI"
    displayName: "DEV Deploy: Weather API"
    dependsOn: DevInfra
    jobs:
      - deployment: "DeployAPI"
        displayName: 'Deploy API'
        pool: Satyam
        environment: Dev
        strategy:
          runOnce:
            deploy:
              steps: 
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    downloadPath: '$(System.ArtifactsDirectory)/downloads'
                              
                - task: AzureRmWebAppDeployment@4
                  displayName: "Deploy WeatherApp API"
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'ADO-WeatherApp-SC-NonProd'
                    appType: 'webAppLinux'
                    WebAppName: '${{ variables.appserviceNameApi }}-${{ parameters.env }}'
                    packageForLinux: '$(System.ArtifactsDirectory)/**/worldclimateapi.zip'
                    StartupCommand: 'pip install flask;pip install requests;python3 app.py'

  - stage: "QaInfra"
    displayName: "QA Deploy: Infra"
    dependsOn: Build
    jobs:
    
      - deployment: "DeployInfra"
        displayName: 'Deploy Infra'
        pool: Satyam
        environment: Qa
        strategy:
          runOnce:
            deploy:
              steps: 
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    downloadPath: '$(System.ArtifactsDirectory)/downloads'
                  
                - task: AzureResourceManagerTemplateDeployment@3
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: $(serviceConnection)
                    subscriptionId: $(subscriptionId)
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: $(resourceGroup)
                    location: 'North Central US'
                    templateLocation: 'Linked artifact'
                    csmFile: '$(System.ArtifactsDirectory)/downloads/drop/InfraArm/appserviceSatyam/appservice.json'
                    csmParametersFile: '$(System.ArtifactsDirectory)/downloads/drop/InfraArm/appserviceSatyam/parameters-qa.json'
                    deploymentMode: 'Incremental'
      
  - stage: "QaApp"
    displayName: "QA Deploy: Weather App"
    dependsOn: QaInfra
    jobs:
      - deployment: "DeployApp"
        displayName: 'Deploy App'
        pool: Satyam
        environment: Qa
        strategy:
          runOnce:
            deploy:
              steps: 
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    downloadPath: '$(System.ArtifactsDirectory)/downloads'
                  
                - task: AzureRmWebAppDeployment@4
                  displayName: "Deploy WeatherApp Web"
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'ADO-WeatherApp-SC-NonProd'
                    appType: 'webAppLinux'
                    WebAppName: '${{ variables.appserviceNameWeb }}-${{ parameters.env }}'
                    packageForLinux: '$(System.ArtifactsDirectory)/**/weatherapp.zip'
                    StartupCommand: 'apt-get install python3-pip -y;apt-get install zip -y;apt-get install python3-venv -y;python3 -m venv antenv;source antenv/bin/activate;apt-get install pkg-config -y --ignore-missing;apt-get install dos2unix;apt-get install default-libmysqlclient-dev -y --ignore-missing;FILEPATH=$(find . -type f -name odbc17.sh);dos2unix "$FILEPATH";bash $FILEPATH;python3 app.py'
                
                - task: AzureRmWebAppDeployment@4
                  displayName: "Deploy WeatherApp API"
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'ADO-WeatherApp-SC-NonProd'
                    appType: 'webAppLinux'
                    WebAppName: '${{ variables.appserviceNameApi }}-${{ parameters.env }}'
                    packageForLinux: '$(System.ArtifactsDirectory)/**/worldclimateapi.zip'
                    StartupCommand: 'apt-get install python3-venv -y;python3 -m venv antenv;source antenv/bin/activate;pip install flask;pip install requests;python3 run.py'
