# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: Satyam
  vmImage: LAPTOP-RS36BMKA

parameters:
  - name: env
    displayName: Environment to Deploy
    type: string
    default: uat
    values:
      - uat
      - prod

variables:
  - group: 'Infra-${{ parameters.env }}'
  - name: appserviceNameWeb
    value: dk-weatherapp-web
  - name: appserviceNameApi
    value: dk-weatherapp-api

stages:
  - stage: "Build"
    displayName: "Build WeatherApp"
    jobs:
      - job: "BuildWeatherapp"
        displayName: 'Build Weatherapp'
        pool: Satyam
        steps:
          - task: ArchiveFiles@2
            displayName: "Weatherapp web Archive"
            inputs:
              rootFolderOrFile: 'source/weatherapp'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/Apps/weatherapp.zip'
              replaceExistingArchive: true
          
          - task: ArchiveFiles@2
            displayName: "Weatherapp API Archive"
            inputs:
              rootFolderOrFile: 'source/WorldClimateApi'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/Apps/worldclimateapi.zip'
              replaceExistingArchive: true
          
          - task: CopyFiles@2
            displayName: "Copy Infra files"
            inputs:
              SourceFolder: 'Pipelines/Infra/ARMTemplates'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/InfraArm'
          
          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifacts"
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  
  - stage: "UATInfra"
    displayName: "UAT Deploy: Infra"
    dependsOn: Build
    jobs:
      - deployment: "DeployInfra"
        displayName: 'Deploy Infra'
        pool: Satyam
        environment: UAT
        strategy:
          runOnce:
            deploy:
              steps: 
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    downloadPath: '$(System.ArtifactsDirectory)/downloads'
                  
                - task: PowerShell@2
                  inputs:
                    targetType: 'inline'
                    script: |
                      # Write your PowerShell commands here.
                      
                      echo ${env:APIVERSION}
                    
                - task: AzureResourceManagerTemplateDeployment@3
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: $(serviceConnection)
                    subscriptionId: $(subscriptionId)
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: $(resourceGroup)
                    location: 'North Central US'
                    templateLocation: 'Linked artifact'
                    csmFile: '$(System.ArtifactsDirectory)/downloads/drop/InfraArm/appserviceSatyam/appservice.json'
                    csmParametersFile: '$(System.ArtifactsDirectory)/downloads/drop/InfraArm/appserviceSatyam/parameters-uat.json'
                    deploymentMode: 'Incremental'

  - stage: "UATApp"
    displayName: "UAT Deploy: Weather App"
    dependsOn: UATInfra
    jobs:
      - deployment: "DeployApp"
        displayName: 'Deploy App'
        pool: Satyam
        environment: UAT
        strategy:
          runOnce:
            deploy:
              steps: 
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    downloadPath: '$(System.ArtifactsDirectory)/downloads'
                  
                - task: AzureRmWebAppDeployment@4
                  displayName: "Deploy WeatherApp Web"
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'NewFreeTrial2024'
                    appType: 'webAppLinux'
                    WebAppName: '${{ variables.appserviceNameWeb }}-${{ parameters.env }}'
                    packageForLinux: '$(System.ArtifactsDirectory)/**/weatherapp.zip'
                    StartupCommand: 'apt-get install python3-pip -y;apt-get install zip -y;apt-get install python3-venv -y;python3 -m venv antenv;source antenv/bin/activate;apt-get install pkg-config -y --ignore-missing;apt-get install dos2unix;apt-get install default-libmysqlclient-dev -y --ignore-missing;FILEPATH=$(find . -type f -name odbc17.sh);dos2unix "$FILEPATH";bash $FILEPATH;python3 app.py'
                  
                - task: AzureRmWebAppDeployment@4
                  displayName: "Deploy WeatherApp API"
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'NewFreeTrial2024'
                    appType: 'webAppLinux'
                    WebAppName: '${{ variables.appserviceNameApi }}-${{ parameters.env }}'
                    packageForLinux: '$(System.ArtifactsDirectory)/**/worldclimateapi.zip'
                    StartupCommand: 'apt-get install python3-venv -y;python3 -m venv antenv;source antenv/bin/activate;pip install flask;pip install requests;python3 run.py'

  - stage: "PRODInfra"
    displayName: "PROD Deploy: Infra"
    dependsOn: Build
    jobs:
      - deployment: "DeployInfra"
        displayName: 'Deploy Infra'
        pool: Satyam
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps: 
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    downloadPath: '$(System.ArtifactsDirectory)/downloads'
                  
                - task: PowerShell@2
                  inputs:
                    targetType: 'inline'
                    script: |
                      # Write your PowerShell commands here.
                      
                      echo ${env:APIVERSION}
                    
                - task: AzureResourceManagerTemplateDeployment@3
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: $(serviceConnection)
                    subscriptionId: $(subscriptionId)
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: $(resourceGroup)
                    location: 'North Central US'
                    templateLocation: 'Linked artifact'
                    csmFile: '$(System.ArtifactsDirectory)/downloads/drop/InfraArm/appserviceSatyam/appservice.json'
                    csmParametersFile: '$(System.ArtifactsDirectory)/downloads/drop/InfraArm/appserviceSatyam/parameters-prod.json'
                    deploymentMode: 'Incremental'

  - stage: "PRODApp"
    displayName: "PROD Deploy: Weather App"
    dependsOn: PRODInfra
    jobs:
      - deployment: "DeployApp"
        displayName: 'Deploy App'
        pool: Satyam
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps: 
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    downloadPath: '$(System.ArtifactsDirectory)/downloads'
                  
                - task: AzureRmWebAppDeployment@4
                  displayName: "Deploy WeatherApp Web"
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: $(serviceConnection)
                    appType: 'webAppLinux'
                    WebAppName: '${{ variables.appserviceNameWeb }}-${{ parameters.env }}'
                    packageForLinux: '$(System.ArtifactsDirectory)/**/weatherapp.zip'
                    StartupCommand: 'apt-get install python3-pip -y;apt-get install zip -y;apt-get install python3-venv -y;python3 -m venv antenv;source antenv/bin/activate;apt-get install pkg-config -y --ignore-missing;apt-get install dos2unix;apt-get install default-libmysqlclient-dev -y --ignore-missing;FILEPATH=$(find . -type f -name odbc17.sh);dos2unix "$FILEPATH";bash $FILEPATH;python3 app.py'
                  
                - task: AzureRmWebAppDeployment@4
                  displayName: "Deploy WeatherApp API"
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: $(serviceConnection)
                    appType: 'webAppLinux'
                    WebAppName: '${{ variables.appserviceNameApi }}-${{ parameters.env }}'
                    packageForLinux: '$(System.ArtifactsDirectory)/**/worldclimateapi.zip'
                    StartupCommand: 'apt-get install python3-venv -y;python3 -m venv antenv;source antenv/bin/activate;pip install flask;pip install requests;python3 run.py'
