trigger:
- none

pool:
  name: Default
  vmImage: chaitanya

parameters:
  - name: environment
    displayName: Environment Select
    type: string
    default: Dev
    values:
      - Dev
      - Qa
      - Uat
      - Prod
variables:
  -group: Credentials
stages:
  - stage: build
    displayName: Build
    jobs:
      - job: "BuildArtifact"
        displayName: "Build Artifact"
        steps:
          - task: ArchiveFiles@2
            displayName: Archive Source/WeatherApp
            inputs:
              rootFolderOrFile: 'Source/WeatherApp'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/Apps/WeatherApp.zip'
              replaceExistingArchive: true
          - task: CopyFiles@2
            displayName: Copy ARM Templates to drop
            inputs:
              SourceFolder: 'Pipelines/Infra/ARMTemplates'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/ARMtemplates'
          - task: CopyFiles@2
            displayName: Copy Pwershell Scripts to drop
            inputs:
              SourceFolder: 'Pipelines/Scripts'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/PowershellScripts'
          - task: PublishBuildArtifacts@1
            displayName: "Publish Artifact: drop"
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  - stage: "InfraDeployment"
    displayName: "Deploy : Infra-${{ parameters.environment }}"
    dependsOn: build
    jobs:
      - deployment: "DeployInfra"
        displayName: "Deploy Infra"
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
             steps:
               - task: DownloadBuildArtifacts@1
                 inputs:
                   buildType: 'current'
                   downloadType: 'single'
                   artifactName: 'drop'
                   downloadPath: '$(System.ArtifactsDirectory)'
               
  - stage: "AppDeploy"
    displayName: "Deploy : App-${{ parameters.environment }}"
    dependsOn: InfraDeployment
    jobs:
      - deployment: "DeployApp"
        displayName: "Deploy App"
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
             steps:
               - task: DownloadBuildArtifacts@1
                 inputs:
                   buildType: 'current'
                   downloadType: 'single'
                   artifactName: 'drop'
                   downloadPath: '$(System.ArtifactsDirectory)'
               - task: PowerShell@2
                 inputs:
                   targetType: 'inline'
                   script: |
                     Get-ChildItem $(System.ArtifactsDirectory)/drop